/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateDataOrderRequestGeoJSONFeature } from './createDataOrderRequestGeoJSONFeature';


/**
 * The Create Data Order request body in GeoJSON FeatureCollection format.
 */
export interface CreateDataOrderRequestBody { 
    type: string;
    features: Array<CreateDataOrderRequestGeoJSONFeature>;
}
