/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataOrderResponseGeoJSONFeature } from './dataOrderResponseGeoJSONFeature';


/**
 * Data order response.
 */
export interface DataOrderResponse { 
    type: string;
    features: Array<DataOrderResponseGeoJSONFeature>;
    /**
     * The client provided id to identify the order.
     */
    id?: string;
    /**
     * The timestamp of the order is created.
     */
    createdDateTime?: Date;
    /**
     * The timestamp of the order is last modified.
     */
    lastModifiedDateTime?: Date;
    /**
     * The timestamp of the order is expired.
     */
    expirationDateTime?: Date;
    /**
     * The timestamp of the order is placed.
     */
    placedDateTime?: Date;
    /**
     * Allocation state of the cluster. Possible values are: NotStarted - Indicates that the data order is created and has not been placed yet. Running - Indicates that the data order is placed and currently being processed. Succeeded - Indicates that the data order has been delivered and produced dataset is ready. Failed - Indicates that the data order has stopped and failed to successfully deliver.
     */
    readonly status?: DataOrderResponse.StatusEnum;
    /**
     * Status details of the order.
     */
    readonly statusDetail?: string;
    /**
     * Price of the order in dollar.
     */
    readonly price?: number;
}
export namespace DataOrderResponse {
    export type StatusEnum = 'NotStarted' | 'Running' | 'Succeeded' | 'Failed';
    export const StatusEnum = {
        NotStarted: 'NotStarted' as StatusEnum,
        Running: 'Running' as StatusEnum,
        Succeeded: 'Succeeded' as StatusEnum,
        Failed: 'Failed' as StatusEnum
    };
}
