/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJSONGeometryGA } from './geoJSONGeometryGA';


/**
 * GeoJSON Feature
 */
export interface GeoJSONFeatureBase { 
    /**
     * feature
     */
    type?: string;
    geometry?: GeoJSONGeometryGA;
    /**
     * feature
     */
    id?: string;
}
