/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJSONLinearRingGA } from './geoJSONLinearRingGA';


/**
 * A valid `GeoJSON` geometry object. Please refer to [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1) for details.
 */
export interface GeoJSONGeometryGA { 
    /**
     * Specifies the `GeoJSON` geometry type. Only `Polygon` is supported.
     */
    type: GeoJSONGeometryGA.TypeEnum;
    /**
     * 
     */
    coordinates: Array<GeoJSONLinearRingGA>;
}
export namespace GeoJSONGeometryGA {
    export type TypeEnum = 'Polygon';
    export const TypeEnum = {
        Polygon: 'Polygon' as TypeEnum
    };
}
