/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJSONFeatureBase } from './geoJSONFeatureBase';

/**
 * The marketplace product data in GeoJSON Feature format.
 */
export interface GetMarketplaceDataResponseGeoJSONFeature extends GeoJSONFeatureBase { 
    /**
     * The properties of the GeoJSON Feature.
     */
    properties: any;
}
