/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetMarketplaceDataResponseGeoJSONFeature } from './getMarketplaceDataResponseGeoJSONFeature';
import { PageResult } from './pageResult';


/**
 * The Get Marketplace Data response object in GeoJSON FeatureCollection format.
 */
export interface GetMarketplaceDataResponse extends PageResult { 
    type?: string;
    features?: Array<GetMarketplaceDataResponseGeoJSONFeature>;
}
