/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataOrderResponse } from './dataOrderResponse';
import { PageResult } from './pageResult';


/**
 * List Data Orders response.
 */
export interface ListDataOrdersResponse extends PageResult { 
    /**
     * The orders.
     */
    readonly orders?: Array<DataOrderResponse>;
}
