/**
 * Azure Maps Data Ordering Service
 * Azure Maps Data Ordering REST APIs
 *
 * OpenAPI spec version: 2021-03-01-preview
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ODataError } from './oDataError';


/**
 * This response object is returned when an error occurs in the Maps API.
 */
export interface ODataErrorResponse { 
    error?: ODataError;
}
